### PR TITLE
Fix error when loading resource text without an actual Python module

### PR DESCRIPTION
**Pull request by beholders-eye**
Fixes this error:

```bash
    from playwright_stealth import stealth_sync
../../../../.cache/pypoetry/virtualenvs/*******-py3.9/lib/python3.9/site-packages/playwright_stealth/__init__.py:1: in <module>
    from playwright_stealth.stealth import stealth_sync, stealth_async, StealthConfig
../../../../.cache/pypoetry/virtualenvs/*******-py3.9/lib/python3.9/site-packages/playwright_stealth/stealth.py:16: in <module>
    'webdrive': from_file('navigator.webdriver.js'),
../../../../.cache/pypoetry/virtualenvs/*******-py3.9/lib/python3.9/site-packages/playwright_stealth/stealth.py:12: in from_file
    return resources.read_text(f'{__package__}.js', name)
/usr/x86_64-pc-linux-gnu/lib/python3.9/importlib/resources.py:139: in read_text
    with open_text(package, resource, encoding, errors) as fp:
/usr/x86_64-pc-linux-gnu/lib/python3.9/importlib/resources.py:121: in open_text
    open_binary(package, resource), encoding=encoding, errors=errors)
/usr/x86_64-pc-linux-gnu/lib/python3.9/importlib/resources.py:111: in open_binary
    raise FileNotFoundError(message)
E   FileNotFoundError: 'navigator.webdriver.js' resource not found in 'playwright_stealth.js'
```

Also ran `chmod +x` on two .js files, for the sake of consistency. (Maybe it's my OCD?)

### CODE REVIEW

**Comment by beholders-eye** [comment]
This all based on the fact the `importlib.resources` only work well on Python modules, and `playwright_stealth.js` was only a directory, to be considered a module it needs the `__init__.py` file.

**Comment by beholders-eye** [comment]
Pinging here, since there was no reply in almost two months. 😳

**Comment by dgtlmoon** [comment]
@beholders-eye seems kinda weird that they need to be chmod +x if they are just JS files ?

**Comment by beholders-eye** [comment]
> @beholders-eye seems kinda weird that they need to be chmod +x if they are just JS files ?

The fix isn't about that. I did the chmod so that every .js file had the same permissions. The others were like that.

**Comment by dgtlmoon** [comment]
I think that doesnt help, better to chmod -x the js files... thats not good practice

**Comment by beholders-eye** [comment]
> I think that doesnt help, better to chmod -x the js files... thats not good practice
I could do that, but as I said. Other js files had it, so I thought it was on purpose. WDYT @Granitosaurus ?

**Comment by Granitosaurus** [comment]
The JS files definitely don't need a `chmod +x` - they are never called to be executed. It's just storage for code source that is being passed to playwright in text. 

Regarding `__init__.py` - I wonder why I can't replicate the need for it myself :thinking: 
Let's merge this in though. Having it in doesn't really cost anything.

**Comment by beholders-eye** [comment]
> The JS files definitely don't need a `chmod +x` - they are never called to be executed. It's just storage for code source that is being passed to playwright in text.
> 
> Regarding `__init__.py` - I wonder why I can't replicate the need for it myself thinking Let's merge this in though. Having it in doesn't really cost anything.

I'm using Python 3.10.x, as you surely know. Maybe that's why? Not sure.

**Comment by beholders-eye** [comment]
@Granitosaurus, have you any plans to publish this to PyPi under a different name, or maybe claim your right over the official name?

**Comment by Granitosaurus** [comment]
Honestly, I don't think the current state of this package is good enough for pypi :grimacing: 
I have a rework branch WIP though I'm not sure when I'm going to finish it.

**Pull request merged**
